Pull license key from environment
newrelic/newrelic-fluentd-output pull request #38
Opened 2021-02-05 18:26 UTC by rittneje

When running fluentd as a pod in Kubernetes, it is better to specify the license as an environment variable from a secret rather writing in the fluentd config.

2021-02-05 18:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/newrelic/newrelic-fluentd-output?pullRequest=38) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/newrelic/newrelic-fluentd-output?pullRequest=38) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/newrelic/newrelic-fluentd-output?pullRequest=38) it.</sub>

2021-02-11 18:35 UTC, rittneje commented
The "failure" is just because it cannot publish the test results. The build itself passed.
>  github.GithubException.GithubException: 403 {"message": "Resource not accessible by integration", "documentation_url": "https://docs.github.com/rest/reference/checks#create-a-check-run"}

2021-02-18 04:20 UTC, rittneje commented
ping @jsubirat

2021-02-23 14:41 UTC, jsubirat commented
Hi @rittneje ! Thank you for your contribution. I'd like to understand why can't we just pass the license key via a `ConfigMap`, similarly to how we do it in our FluentBit-based Helm chart (see [here](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/templates/configmap.yaml#L51)). Then, the license key can be read from a secret (see [here](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/templates/configmap.yaml#L51)). What is the advantage of doing it this way (or the drawback of using a `ConfigMap`)? Thank you in advance!

2021-02-23 18:06 UTC, rittneje commented
@jsubirat I'm assuming you are referring to the ConfigMap containing the fluentd configuration XML. There are two reasons the license key should not be put there.
1. ConfigMaps are specifically not meant to hold any sensitive/secret data. https://kubernetes.io/docs/concepts/configuration/configmap/
2. If you reference an environment variable in the fluentd config (e.g., `#{ENV['NEW_RELIC_LICENSE_KEY']}`), then the value of that environment variable is printed to the fluentd logs at startup (when it prints out its configuration).

Instead, we want to import the license key from a proper Kubernetes secret using `envFrom` in the pod spec.

2021-02-26 16:56 UTC, rittneje commented
ping @jsubirat

2021-03-03 19:37 UTC, rittneje commented
ping @jsubirat

2021-03-08 12:44 UTC, rittneje commented
ping @jsubirat

2021-03-12 05:33 UTC, rittneje commented
ping @jsubirat

2021-03-19 16:56 UTC, rittneje commented
ping @jsubirat

2021-03-25 20:05 UTC, rittneje commented
ping @jsubirat

2021-03-26 17:16 UTC, jsubirat commented
Hi @rittneje , thank you for your answer. First of all, accept my apologies for the delay of our answers. Also, most of my confusion came from the fact that I didn't realize that this was the Fluentd (and not the FluentBit) plugin that we were talking about. 🤦‍♂️ 

Our Kubernetes plugin is based on Fluent Bit, in which the license key is passed to the pod as an environment variable [by reading it from a secret](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/templates/daemonset.yaml#L58-L67), but it is never "stored" in the ConfigMap. It is actually "[referenced](https://github.com/newrelic/helm-charts/blob/master/charts/newrelic-logging/templates/configmap.yaml#L51)" there, and [resolved by FluentBit](https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/variables) when starting. A similar thing could be achieved [with Fluentd](https://docs.fluentd.org/quickstart/faq#how-can-i-use-environment-variables-to-configure-parameters-dynamically).

As of your second point, that's a really good catch! I was not aware of the configuration being printed in Fluentd. I'm mostly experienced in using FluentBit, which doesn't print out its configuration/env variables upon start. That's what confused me in the first place.

Please let us have some discussion about this change within our team, since we would like to offer a standard set of features across our forwarding plugins. On the meantime, would it be an option for you to use Fluent Bit instead? Have you considered our [K8s Helm chart](https://github.com/newrelic/helm-charts/tree/master/charts/newrelic-logging)?

I'll try to come back to you with a conclusive answer/approval ASAP, nonetheless. Apologies again for the delay and thanks a lot for your patience and contributions.

2021-03-29 19:47 UTC, rittneje commented
@jsubirat We can look into FluentBit, but that seems like a bigger transition than we are prepared to deal with at this time. Personally, I feel that it is the Fluentd and FluentBit plugins that should be changed, given that all of your SDKs just use the `NEW_RELIC_LICENSE_KEY` environment variable automatically without any extra configuration.

2021-03-31 09:49 UTC, jsubirat requested changes
Thanks a lot @rittneje for your contribution. I left a few comments, could you please check them? Thanks a lot.

2021-03-31 09:49 UTC, jsubirat commented on lib/fluent/plugin/out_newrelic.rb
> +        @license_key ||= ENV["NEW_RELIC_LICENSE_KEY"]
Could you please also add support for the API key being passed via environment variables?

```suggestion
        @api_key ||= ENV["NEW_RELIC_API_KEY"]
        @license_key ||= ENV["NEW_RELIC_LICENSE_KEY"]
```

2021-03-31 09:49 UTC, jsubirat commented on README.md
> +If neither is specified, then it will use the NEW_RELIC_LICENSE_KEY environment variable, if set.
Please also mention `NEW_RELIC_API_KEY` here, including the fact that `NEW_RELIC_API_KEY` will take precedence over `NEW_RELIC_LICENSE_KEY`.

2021-03-31 09:49 UTC, jsubirat commented on lib/newrelic-fluentd-output/version.rb
> +  VERSION = "1.1.12"
Please update the `minor` version instead
```suggestion
  VERSION = "1.2.0"
```

2021-04-14 14:27 UTC, rittneje commented
ping @jsubirat

2021-04-19 14:21 UTC, rittneje commented
ping @jsubirat

2021-04-26 15:25 UTC, rittneje commented
ping @jsubirat

2021-05-04 14:33 UTC, jsubirat commented
Hi @rittneje , please forgive me. I don't know what's going on but I haven't received any notification from this PR since I last reviewed it. Thanks for taking care of addressing the comments, and for your nice contribution. 🙇

2021-05-04 14:34 UTC, jsubirat approved these changes

2021-05-04 14:41 UTC, jsubirat commented
Hi @rittneje, for future PRs, please create a branch directly in the repo in order to not face this permissions issue again. We'll add this in the README as well, thanks a lot for reporting it.

2021-05-04 14:41 UTC, merged